import Image from 'next/image';
import { SiteLink as Link } from '@/components/site-link';
import { ArrowDownRight, ArrowRight, ArrowUpRight, Check } from 'lucide-react';
import { CtaBand } from '@/components/cta-band';
import { VideoFacade } from '@/components/video-facade';
import { services } from '@/lib/site-data';

export default function Home() { return <>
  <section className="home-hero"><Image src="/images/performance-primary.jpg" alt="Team Kinetix performer airborne above a large stadium audience" fill priority sizes="100vw" className="object-cover object-[52%_36%]" /><div className="hero-shade" /><div className="hero-lines" aria-hidden="true" /><div className="site-container relative z-10 flex min-h-[calc(100svh-5rem)] flex-col justify-end pb-12 pt-32 lg:min-h-[760px] lg:pb-16"><p className="eyebrow">Parkour · Freerunning · Acrobatics · Action</p><h1 className="max-w-6xl">Performance<br /><span>without limits.</span></h1><div className="mt-8 flex flex-col items-start gap-6 sm:flex-row sm:items-center"><Link className="button button-primary" href="/contact">Discuss your event <ArrowUpRight /></Link><Link className="inline-arrow" href="/showreel">Watch Team Kinetix <ArrowDownRight /></Link></div><div className="mt-12 grid gap-4 border-t border-white/20 pt-6 text-sm font-bold uppercase tracking-widest text-white/70 sm:grid-cols-3"><span>Spectacular for audiences</span><span>Practical for producers</span><span>Built around your brief</span></div></div></section>
  <section className="section-pad bg-white text-[var(--ink)]"><div className="site-container grid gap-10 lg:grid-cols-[.72fr_1.28fr]"><p className="eyebrow text-[var(--purple)]">Team Kinetix</p><div><h2 className="display-heading max-w-4xl">Extraordinary movement, shaped for live audiences and productions.</h2><p className="mt-8 max-w-2xl text-lg leading-relaxed text-black/60">Team Kinetix brings parkour, freerunning and acrobatics into professional entertainment. From a first creative conversation to the final landing, each performance is developed around the space, audience and ambition of the project.</p></div></div></section>
  <section className="section-pad bg-[var(--ink)]"><div className="site-container"><div className="section-heading"><div><p className="eyebrow">What we do</p><h2>Three ways to move<br />your project forward.</h2></div><p>Performance is the headline. Planning and specialist expertise make it possible.</p></div><div className="service-grid mt-14">{services.map((service) => { const Icon = service.icon; return <Link href={service.href} key={service.title} className="service-card"><span className="service-number">{service.number}</span><Icon aria-hidden="true" /><h3>{service.title}</h3><p>{service.text}</p><span className="card-link">{service.cta} <ArrowRight /></span></Link>; })}</div></div></section>
  <section className="section-pad bg-[#f3f0f5] text-[var(--ink)]"><div className="site-container"><div className="section-heading"><div><p className="eyebrow text-[var(--purple)]">Selected experience</p><h2>Proven in front of<br />the biggest audiences.</h2></div><p className="!text-black/60">From live television and international festivals to landmark openings, theatre and film.</p></div><div className="work-gallery mt-14"><article><div className="work-image"><Image src="/images/performance-cricket.jpg" alt="Team Kinetix acrobatic performance with flame effects at a televised NatWest T20 cricket match" fill sizes="(max-width: 768px) 100vw, 40vw" className="object-cover" /></div><p className="eyebrow text-[var(--purple)]">2015–2016</p><h3>Every televised NatWest T20 match</h3></article><article><div className="work-image"><Image src="/images/performance-battersea.jpg" alt="Team Kinetix performers delivering a coordinated acrobatic sequence at Battersea Power Station" fill sizes="(max-width: 768px) 100vw, 40vw" className="object-cover" /></div><p className="eyebrow text-[var(--purple)]">Landmark openings</p><h3>King’s Cross and Battersea Power Station</h3></article><article><div className="work-image work-image-portrait"><Image src="/images/performance-acrobatics.jpg" alt="Team Kinetix acrobat performing an aerial rotation at an international event" fill sizes="(max-width: 768px) 100vw, 25vw" className="object-cover" /></div><p className="eyebrow text-[var(--purple)]">International</p><h3>Festivals and private events worldwide</h3></article></div><div className="mt-12 flex flex-wrap gap-x-10 gap-y-4 border-t border-black/15 pt-8 font-bold uppercase tracking-widest text-black/55"><span>Britain’s Got Talent</span><span>British Fashion Awards</span><span>Nissan</span><span>Sky Sports</span><span>English National Opera</span></div></div></section>
  <section className="section-pad overflow-hidden bg-[var(--purple)] text-white"><div className="site-container grid items-center gap-12 lg:grid-cols-[.85fr_1.15fr]"><div><p className="eyebrow">See the work</p><h2 className="display-heading">Movement makes sense in motion.</h2><p className="mt-6 max-w-lg text-lg text-white/65">Watch Team Kinetix perform across live entertainment and screen. Then tell us what you want your audience to feel.</p><Link href="/showreel" className="inline-arrow mt-8">See Kinetix in action <ArrowUpRight /></Link></div><div className="media-cut"><VideoFacade id="Is4t7XojeIQ" title="Kinetix Acroblast acrobats at T20 cricket" image="https://i.ytimg.com/vi/Is4t7XojeIQ/hqdefault.jpg" /></div></div></section>
  <section className="section-pad bg-[#f3f0f5] text-[var(--ink)]"><div className="site-container grid gap-12 lg:grid-cols-2 lg:gap-20"><div className="relative min-h-[560px] overflow-hidden rounded-[2rem]"><Image src="/images/team-kinetix-about.jpg" alt="Team Kinetix athlete vaulting over a performance obstacle" fill sizes="(max-width: 1024px) 100vw, 50vw" className="object-cover" /></div><div className="self-center"><p className="eyebrow text-[var(--purple)]">Why Team Kinetix</p><h2 className="display-heading">Creative ambition. Professional delivery.</h2><div className="feature-list mt-9">{['A performance company built from genuine movement expertise','Bespoke thinking for different spaces and audiences','Experience spanning corporate entertainment, theatre and screen','One team for performance, practical support and specialist advice'].map((item) => <div key={item}><Check /><span>{item}</span></div>)}</div><Link className="button button-dark mt-9" href="/about">Meet Team Kinetix <ArrowUpRight /></Link></div></div></section>
  <CtaBand title="Bring Kinetix to your next event." />
</>; }
